### ISSUE TITLE
OpenNI.org

### ISSUE THREAD

**Issue by devsnek** [OpenNI/OpenNI#102]
OpenNI.org doesn't exist any more!

**Comment by devsnek** [comment]
And neither does primesense.org

**Comment by wakaru44** [comment]
http://createdigitalmotion.com/2014/02/open-kinect-tools-go-closed-and-dead-limiting-artist-and-hacker-options-call-for-help/
:,(

**Comment by qrqiuren** [comment]
奠

**Comment by FingerLiu** [comment]
苹果是开源的毒瘤？

**Comment by tamarous** [comment]
http://openni.ru/
It works.

**Comment by BigBlueHat** [comment]
It now goes to apple.com...

**Comment by BigBlueHat** [comment]
Ah. Seems someone is rescuing it: http://structure.io/openni
