### ISSUE TITLE
Linux  Arm Build Error  

### ISSUE THREAD

**Issue by praveen-science** [OpenNI/OpenNI#104]
I am getting following error when i trying to build OpenNI in to Linux Arm any body can help ? 

---
-   PrimeSense OpenNI Redist    *
-     2015-08-04 17:22:44       *
  *********************************

Target: Linux-Arm
Version: 1.5.7.10
Num of compile jobs: 8
- Building OpenNI...
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnFPSCalculator.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnFPSCal                                                                                                                                                             culator.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnQueries.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnQuerie                                                                                                                                                             s.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnProfiling.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnProfil                                                                                                                                                             ing.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnTypeManager.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnTypeMa                                                                                                                                                             nager.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnLogFileWriter.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnLogFil                                                                                                                                                             eWriter.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnUSB.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnUSB.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnDumpFileWriter.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnDumpFi                                                                                                                                                             leWriter.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnLogConsoleWriter.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnLogCon                                                                                                                                                             soleWriter.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnLicensing.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnLicens                                                                                                                                                             ing.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnBaseNode.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnBaseNo                                                                                                                                                             de.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnEnumerationErrors.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnEnumer                                                                                                                                                             ationErrors.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnLog.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnLog.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnOSMemoryProfiling.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnOSMemo                                                                                                                                                             ryProfiling.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnRecorderImpl.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnRecord                                                                                                                                                             erImpl.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnExportedNodes.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnExport                                                                                                                                                             edNodes.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnModuleLoader.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnModule                                                                                                                                                             Loader.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnXml.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnXml.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnUtils.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnUtils.                                                                                                                                                             o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/openNI.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/openNI.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnScheduler.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnSchedu                                                                                                                                                             ler.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnPlayerImpl.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnPlayer                                                                                                                                                             Impl.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnXmlScriptNodeExporter.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnXmlScr                                                                                                                                                             iptNodeExporter.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnOS.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnOS.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnNodeWatcher.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnNodeWa                                                                                                                                                             tcher.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnMockNotifier.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnMockNo                                                                                                                                                             tifier.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnNodeManager.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnNodeMa                                                                                                                                                             nager.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnStatusRegister.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnStatus                                                                                                                                                             Register.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnDump.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnDump.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnXmlScriptNode.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnXmlScr                                                                                                                                                             iptNode.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnOpenNI.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnOpenNI                                                                                                                                                             .o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnLogAndroidWriter.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnLogAnd                                                                                                                                                             roidWriter.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxProcesses.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxPro                                                                                                                                                             cesses.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxMutex.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxMut                                                                                                                                                             ex.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxSharedMemory.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxSha                                                                                                                                                             redMemory.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxPosixNamedEvents.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxPos                                                                                                                                                             ixNamedEvents.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxStrings.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxStr                                                                                                                                                             ings.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxCriticalSections.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxCri                                                                                                                                                             ticalSections.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxPosixEvents.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxPos                                                                                                                                                             ixEvents.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxUSBDevice.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxUSB                                                                                                                                                             Device.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxMemory.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxMem                                                                                                                                                             ory.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxThreads.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxThr                                                                                                                                                             eads.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxSharedLibs.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxSha                                                                                                                                                             redLibs.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxDebug.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxDeb                                                                                                                                                             ug.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxINI.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxINI                                                                                                                                                             .o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxNetwork.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxNet                                                                                                                                                             work.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxKeyboard.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxKey                                                                                                                                                             board.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxEvents.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxEve                                                                                                                                                             nts.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/XnUSBLinux.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnUSBLin                                                                                                                                                             ux.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxSysVNamedEvents.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxSys                                                                                                                                                             VNamedEvents.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxFiles.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxFil                                                                                                                                                             es.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/LinuxTime.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/LinuxTim                                                                                                                                                             e.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/tinystr.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/tinystr.                                                                                                                                                             o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/tinyxmlerror.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/tinyxmle                                                                                                                                                             rror.o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/tinyxml.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/tinyxml.                                                                                                                                                             o
  /usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register argumen                                                                                                                                                             ts, ./Arm-Release/tinyxmlparser.o does not
  /usr/bin/ld: failed to merge target specific data of file ./Arm-Release/tinyxmlp                                                                                                                                                             arser.o
  collect2: ld returned 1 exit status
  make[1]: **\* [../../Bin/Arm-Release/libOpenNI.so] Error 1
  make: **\* [OpenNI] Error 2
  failed to execute: make  -j8 -C /home/pi/OpenNI/Platform/Linux/CreateRedist/../B                                                                                                                                                             uild > /home/pi/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!

**Comment by praveen-science** [comment]
I am probably compiling on a linaro version newer than 12.x. Linaro had switched to hard-floats. Try removing the "-mfloat-abi=softfp" flag from Platform/Linux/Build/Common/Platform.ARM file.

**Comment by schelian** [comment]
For what it's worth, Praveen's step helped me compiling on a NVIDIA Jetson TK1.  Thanks!
