### ISSUE TITLE
.NET Wrapper: CodecIDs

### ISSUE THREAD

**Issue by Patrock** [OpenNI/OpenNI#11]
in the file wrappers.cs there is an error regarding the codecID-creation.

the c#-version shifts the bytes from first to last, the c-version does this from last byte to first byte. The generated codesc in the .NET wrapper are undefined and can't be laoded.

c#:
public CodecID(byte byte1, byte byte2, byte byte3, byte byte4) :
            this((UInt32)(byte4 << 24 | byte3 << 16 | byte2 << 8 | byte1))
        {
        }

c:
# define XN_CODEC_ID(c1, c2, c3, c4) (XnCodecID)((c4 << 24) | (c3 << 16) | (c2 << 8) | c1)

With kind regards

Patrock

**Comment by aalmada** [comment]
Fixed in my fork. 
Thanks for reporting!

**Comment by OpenNI** [comment]
Fixed.
