### ISSUE TITLE
WaitAndUpdate not waiting for AlternativeViewPoint

### ISSUE THREAD

**Issue by sebjoh** [OpenNI/OpenNI#12]
I have a setup with two production nodes (kinect sensor using drivers from https://github.com/avin2/SensorKinect). I used to call `WaitAnyUpdateAll()` to have the data updated and it worked fine. Now I have added AlternativeViewPoint to my depthnode and many frames now appears to be incomplete (with lower rows all black) when `WaitAnyUpdateAll()` returns.

To solve this I substituted `WainAnyUpdateAll` for `WaitOneUpdateAll(depthGenerator)` followed by `imageGenerator.WaitAndUpdateData()`. This resoloved the issue as long as the sensor was connected, but not when playing data from a prerecorded file.

My XML-config:
`<?xml version="1.0" encoding="UTF-8"?>
<OpenNI>
    <Licenses>
        
        
    </Licenses>
    <Log writeToConsole="false" writeToFile="true">
        
        <LogLevel value="3"/>
        <Masks>
            <Mask name="ALL" on="true"/>
        </Masks>
        <Dumps>
        </Dumps>
    </Log>
    <ProductionNodes>
        <Node type="Image" name="Image1">
            <Configuration>
                <MapOutputMode xRes="640" yRes="480" FPS="30"/>
                <Mirror on="true"/>
            </Configuration>
        </Node>
        <Node type="Depth" name="Depth1">
            <Configuration>
                <MapOutputMode xRes="640" yRes="480" FPS="30"/>
                <AlternativeViewPoint>Image1</AlternativeViewPoint>
                <Mirror on="true"/>
                
            </Configuration>
        </Node>

```
    <!-- Recorder node. Comment out when not used -->
    <!-- can use "NONE" or "16zP" as codec -->
    <!--
    <Node type="Recorder" name="Recorder1"> 
        <Configuration> 
            <RecorderDestination medium="File" name="recordKinectView_NONE.oni"/> 
            <AddNodeToRecording name="Image1" codec="NONE"/>
            <AddNodeToRecording name="Depth1" codec="NONE"/> 
        </Configuration> 
    </Node>
    -->
</ProductionNodes>
```

</OpenNI>
`

**Comment by OpenNI** [comment]
This was fixed in the stable release of OpenNI (1.5.2)
Ziv.
