### ISSUE TITLE
Nite (?) crash on Mac OS X

### ISSUE THREAD

**Issue by mkoppanen** [OpenNI/OpenNI#16]
Hi,

I am seeing the following crash on Mac OS X with latest OpenNI / Nite:

Thread 5 Crashed:
0   libXnVFeatures_1_3_1.dylib      0x0000000123c3ba51 RobustICP::InitialCellSegmentation(Box2D<int> const&, double&, double&, Vector3D<double>&, Frame3D<double> const&, DistanceFromEdges const_, Vector3D<double> const&, bool) + 849
1   libXnVFeatures_1_3_1.dylib      0x0000000123c3c65d RobustICP::CreateTorsoCellsAndHead(bool, Array<HeadCandidate>&) + 477
2   libXnVFeatures_1_3_1.dylib      0x0000000123c3cc09 RobustICP::Run(MultiResDepthMapContainer const_, UserInfo const_, Box2D<int>&, bool, PoseCandidateInfo_, BodyParameters_, BodySegmentation_, TorsoDetector_, StateMachine_, DistanceFromEdges_, HeadCandidate_, TorsoFitting_) + 297
3   libXnVFeatures_1_3_1.dylib      0x0000000123b39adc FeatureExtractor::ComputeBestFitTorso(int, double, int) + 3548
4   libXnVFeatures_1_3_1.dylib      0x0000000123b3a4bb FeatureExtractor::Run(int, double, int) + 1947
5   libXnVFeatures_1_3_1.dylib      0x0000000123b3b8e3 FeatureExtractor::Update(int, double, int) + 35
6   libXnVFeatures_1_3_1.dylib      0x0000000123b0a432 MultiUserFeatureExtractor::Update(xn::DepthGenerator const&, xn::DepthMetaData const&, xn::SceneMetaData const&) + 386
7   libXnVFeatures_1_3_1.dylib      0x0000000123aa0a71 XnVSkeletonGenerator::UpdateUsers() + 1809
8   libXnVFeatures_1_3_1.dylib      0x0000000123aa0eff XnVSkeletonGenerator::UpdateData() + 79
9   libOpenNI.dylib                 0x000000010004c848 xnUpdateDataImpl(XnInternalNodeData_) + 88
10  libOpenNI.dylib                 0x0000000100050600 xnUpdateTreeImpl(XnProductionNodesSet_, XnNodeInfo const_) + 1760
11  libOpenNI.dylib                 0x00000001000560a7 xnWaitNoneUpdateAll + 903
12  sensorinput                     0x00000001000109ed OpenNIWrapper::run() + 141
13  libboost_thread-mt.dylib        0x000000010027b209 thread_proxy + 137
14  libSystem.B.dylib               0x00007fff826f84f6 _pthread_start + 331
15  libSystem.B.dylib               0x00007fff826f83a9 thread_start + 13

**Comment by mkoppanen** [comment]
This seems to happen when torso is different element than head. I can reproduce this quite reliably when I am sitting behind a laptop and sensor is pointing at me. Only my head and top part of shoulders are visible to the sensor and torso is covered by the laptop lid.

**Comment by OpenNI** [comment]
This should be fixed in the latest version...

**Comment by julapy** [comment]
would you be able to specify in which version this was fixed?

**Comment by OpenNI** [comment]
In NiTE 1.4.2 and above.
