### ISSUE TITLE
open source and the community

### ISSUE THREAD

**Issue by aalmada** [OpenNI/OpenNI#22]
Open source is more than just making public the source. It is also letting the community contribute to a common goal. 
The number of forks and the activity in these shows the interest that there is. Unfortunately, there has never been a merge from these forks into the official source, issue reports and pull requests are just ignored. Not approved, not reproved or commented. Simply ignored...
That's not the way you create a community. That's not the way you set a standard...
It's been a lot of fun but, with this attitude and the official Kinect SDK comming out, this project as lost all my interest...
My two cents,
aalmada

**Comment by tals** [comment]
No response yet... Is this project dead?

**Comment by OpenNI** [comment]
We are doing our best to improve :-)
Ziv.
