### ISSUE TITLE
problems building OpenNI on ubuntu 10.10

### ISSUE THREAD

**Issue by K22** [OpenNI/OpenNI#28]
thank you so much for this release.
But i 've some problems when i try to build openNI in Ubuntu 10.10 (amd64), with RedistMaker?:

../../../../../Wrappers/OpenNI.jni/methods.inl:314: warning: deprecated conversion from string constant to ‘char_’ /bin/sh: javac: not found make1?: ../../../Bin/Release/org.OpenNI.jar? Error 127 make: Wrappers/OpenNI.java? Error 2 failed to execute: make PLATFORM=x86 -C ../Build > /home/_****/Documents/OpenNI-OpenNI-7fad563/Platform/Linux-x86/CreateRedist?/Output/BuildOpenNI.txt Building Failed!

Does someone solve this error? thanks for your help :)
K.

**Comment by Robotto** [comment]
Looks like a java issue.. have you installed JDK?

**Comment by OpenNI** [comment]
Please follow the readme and install JDK as instructed...
