### ISSUE TITLE
xnContextRunXmlScriptFromFileEx() crashes on repeated loading of config with USER node

### ISSUE THREAD

**Issue by diablodale** [OpenNI/OpenNI#29]
I believe I've isolated an issue with the new generation codebases of:
OpenNI 1.3.2.3 for Win32
PrimeSense NITE 1.4.1.2 for Win32
PrimeSense SensorKinect Win32 Device Driver v0.7 (based on Primesense 5.0.3.4)

Given an XML config file which has a DEPTH, IMAGE, and USER nodes, then repeated reloading of it using xnContextRunXmlScriptFromFileEx() causes a crash in less than 10 reloads.
If there is no USER node, then I can reload it over 100 times (tested) with no issues.

Before each reload, nodes are being released. The crash is not occurring in the releasing. It is instead occurring within xnContextRunXmlScriptFromFileEx()

**Comment by OpenNI** [comment]
This is fixed in NITE 1.5 and above.
Thanks,
Ziv.
