### ISSUE TITLE
OPenNI.net: Context.CreateProductionNodeObject

### ISSUE THREAD

**Issue by Patrock** [OpenNI/OpenNI#30]
Hello, 

i think i discovered a bug in this function. 
When the pinvoke call

[DllImport(openNILibraryName)]
        public static extern ProductionNodeDescription xnNodeInfoGetDescription(XnNodeInfo pNodeInfo);

is done there is a accessviolationexception. When i change the return type to IntPtr and do a Marshal.PtrToStructure on this, i can get the right ProductionNodeDescription...

this seems to solve other problems i had with NodeInfo.instance too... don't know why...

Greetings,

Patrock

**Comment by OpenNI** [comment]
Already fixed.
