### ISSUE TITLE
UserTracker.java sample crashes at pose detection

### ISSUE THREAD

**Issue by HairyFotr** [OpenNI/OpenNI#31]
There seems to be a bug in the Java wrapper, which causes Java programs to crash at pose detection.

The fix which works for me was posted here:
http://stackoverflow.com/questions/6831777/openni-usertracker-java-sample-crashes/7029208#7029208

**Comment by expressoCoder** [comment]
I've created a pull request with the fixes - https://github.com/OpenNI/OpenNI/pull/35

**Comment by OpenNI** [comment]
Fixed...
