### ISSUE TITLE
java/jni xnTellPlayerFrame() raises ClassCastException

### ISSUE THREAD

**Issue by fjenett** [OpenNI/OpenNI#32]
I'm using the Java wrapper (latest unstable Mac release) to read an .oni file. For the following code:
myPlayer.tellFrame( myProductionNode );

i get:
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
    at org.OpenNI.Player.tellFrame(Player.java:101)

In org_OpenNI_NativeMethods.cpp -> Java_org_OpenNI_NativeMethods_xnTellPlayerFrame (starting line 2718) it says:
SetOutArgLongValue( ... )

but it's set to return an "jint" / "int"

There are a couple of native methods that have this combination if jint and SetOutArgLongValue, i wonder if these are maybe wrong too?

**Comment by OpenNI** [comment]
Already fixed.
