### ISSUE TITLE
mixed space and tab in OpenNI/Platform/Win32/CreateRedist/*.py

### ISSUE THREAD

**Issue by tnadmin** [OpenNI/OpenNI#37]
there are mixed use of spaces and tabs in OpenNI/Platform/Win32/CreateRedist/*.py, rendering them not usable at all without fixing manually.
i didn't check the other scripts, but they are likely suffering the same problem too.

**Comment by OpenNI** [comment]
Can you please paste the exact error?
What's the python version you are using?
I cannot reproduce it...

**Comment by tnadmin** [comment]
search for space and/or tabs, you will find them in the indentation.

**Comment by OpenNI** [comment]
All fixed in the latest version.
Thanks!
Ziv.
