### ISSUE TITLE
Java wrapper: createByteBuffer() method in org.OpenNI.Map is not very efficient.

### ISSUE THREAD

**Issue by ushadow** [OpenNI/OpenNI#39]
The method allocates a new buffer each time an image frame is accessed. This  uses a lot of memory and keeps the garbage collector busy all the time. A preferred way would be to allocate the buffer just once in the constructor.

**Comment by ushadow** [comment]
Maybe createByteBuffer() is useful in certain use cases. Then adding a copyToByteBuffer(ByteBuffer buffer) method would be useful.

**Comment by OpenNI** [comment]
It will be part of OpenNI 1.4 which will be released soon, thanks.
