### ISSUE TITLE
RedistMaker error on Mac OS/X 10.6.8

### ISSUE THREAD

**Issue by wilson100hong** [OpenNI/OpenNI#42]
Hi,

  I follow the installation guide and installed libtool and libusb. However, when I run ./RedistMaker under Platform/Linux-x86/CreateRedist, I got such error message:

---
-   PrimeSense OpenNI Redist    *
-     2011-10-12 23:18:46       *
  *********************************
- Taking version...
  version is 1.3.3.6
- Building OpenNI...
  In file included from ../../../../Source/OpenNI/XnDump.cpp:25:
  ../../../../Include/XnDump.h:167: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:168: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:169: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:170: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:171: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:172: warning: ‘warning’ attribute directive ignored
  In file included from ../../../../Source/OpenNI/XnDump.cpp:25:
  ../../../../Include/XnDump.h:167: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:168: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:169: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:170: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:171: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:172: warning: ‘warning’ attribute directive ignored
  In file included from ../../../../Include/XnDumpWriters.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.cpp:4:
  ../../../../Include/XnDump.h:167: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:168: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:169: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:170: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:171: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:172: warning: ‘warning’ attribute directive ignored
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual XnDumpWriterFileHandle XnDumpFileWriter::OpenFile(const XnChar_, XnBool, const XnChar_)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:25: error: invalid conversion from ‘XN_FILE_HANDLE’ to ‘void_’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::Write(XnDumpWriterFileHandle, const XnUInt8_, XnUInt32)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:33: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::CloseFile(XnDumpWriterFileHandle)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:39: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  In file included from ../../../../Include/XnDumpWriters.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.cpp:4:
  ../../../../Include/XnDump.h:167: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:168: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:169: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:170: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:171: warning: ‘warning’ attribute directive ignored
  ../../../../Include/XnDump.h:172: warning: ‘warning’ attribute directive ignored
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual XnDumpWriterFileHandle XnDumpFileWriter::OpenFile(const XnChar_, XnBool, const XnChar_)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:25: error: invalid conversion from ‘XN_FILE_HANDLE’ to ‘void_’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::Write(XnDumpWriterFileHandle, const XnUInt8_, XnUInt32)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:33: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::CloseFile(XnDumpWriterFileHandle)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:39: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  lipo: can't figure out the architecture type of: /var/folders/8L/8LNYMSgEE5mYsWyaUxuEUE+++TI/-Tmp-//ccTxpyjf.out
  make[1]: **\* [Release/XnDumpFileWriter.o] Error 1
  make: **\* [OpenNI] Error 2
  failed to execute: make PLATFORM=x86 -C ../Build > /Users/wilson100/Projects/OpenNI/Platform/Linux-x86/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!
  
  I have update my CMake and any library I can think of but still failed. Can someone tell me which step I miss? Thanks.

**Comment by Emmanuelaudibert** [comment]
Hi,

Encountering exactely the same (bad) issue (thousands of "warning attribute directive ignored" ending by "Building failed!"

Also updated today Cmake, Macports... that seem tu run OK.

But brand new to all this,
any help would be appreciated.
Thanks

**Comment by OpenNI** [comment]
Fixed... sorry about that :-)
Please get the new sources.
Ziv.

**Comment by Emmanuelaudibert** [comment]
Thanks ! That was fast. And sunday though.

Please excuse me if I'm blind but where shall I get the new sources? I mean the links from OpenNI > downloads to GitHub lead to the same files yet (OpenNI-OpenNI-Stable-1.3.3.6-0-g41646a5 and OpenNI-OpenNI-Unstable-1.3.4.3-0-gd8116f2)...
Anyway, I downloaded half an hour ago the stable version (aged about 7 hours ago, "Fixed compilation problems"...) and tried to build it but no, appears to be exactly the same as yesterday, including same failed issue.

Maybe trying tomorrow, time for you to push new files?

And last question if I may, do you think it's better (whether imperative?) to uninstall / clean some things or others before my next try to install OpenNI? If so, I'm not sure to find the best way (no uninstall.sh visible) as I'm pretty a (happy) beginner to code's questions.

Please let me know when you may have something,
Thanks again for your quick replying,

Emmanuel

Le 16 oct. 2011  15:29, OpenNI a crit :

**Comment by OpenNI** [comment]
You are right, sorry about that, there was a problem a "bad" rename of a file name from the java wrappers in the GitHub.

I've fixed it and all should be well now.

Can you please get the sources and try again?

Ziv.

**Comment by Emmanuelaudibert** [comment]
Thanks for that !
But in the meanwhile, I found and launched "Zigfu installer"... and  
that works ! I mean the Ni viewer appeared and the tracking is OK.

Now I'm wrestling with OSCeleton. Doesn't seem to be alive yet... Any  
clue??? f I may...

Do you suggest I try your new sources anyway? Would it be better for  
OSCeleton?

Well, last step before I can run my lovely MaxMSP and make puppets  
dancing.

Thanks again for your concern,
Emmanuel

**Comment by chemplife** [comment]
1st-workstation:CreateRedist ratulaggarwal$ sudo ./RedistMaker

---
-   PrimeSense OpenNI Redist    *
-     2015-02-23 12:58:37       *
  *********************************

Target: MacOSX
Version: 1.5.7.10
Num of compile jobs: 4
- Building OpenNI...
  ld: warning: ignoring file /usr/local/lib/libusb-1.0.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libusb-1.0.dylib
  Undefined symbols for architecture i386:
  "_libusb_alloc_transfer", referenced from:
      _xnUSBInitReadThread in XnUSBLinux.o
  "_libusb_bulk_transfer", referenced from:
      _xnUSBWriteEndPoint in XnUSBLinux.o
      _xnUSBReadEndPoint in XnUSBLinux.o
  "_libusb_cancel_transfer", referenced from:
      xnUSBReadThreadMain(void_) in XnUSBLinux.o
  "_libusb_claim_interface", referenced from:
      _xnUSBOpenDeviceImpl in XnUSBLinux.o
  "_libusb_close", referenced from:
      _xnUSBOpenDeviceImpl in XnUSBLinux.o
      _xnUSBCloseDevice in XnUSBLinux.o
  "_libusb_control_transfer", referenced from:
      _xnUSBSendControl in XnUSBLinux.o
      _xnUSBReceiveControl in XnUSBLinux.o
  "_libusb_exit", referenced from:
      xnUSBPlatformSpecificShutdown() in XnUSBLinux.o
  "_libusb_free_config_descriptor", referenced from:
      _xnUSBOpenEndPoint in XnUSBLinux.o
  "_libusb_free_device_list", referenced from:
      FindDevice(unsigned short, unsigned short, void_, libusb_device**) in XnUSBLinux.o
      _xnUSBEnumerateDevices in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_free_transfer", referenced from:
      xnCleanupThreadData(XnUSBReadThreadData_) in XnUSBLinux.o
  "_libusb_get_active_config_descriptor", referenced from:
      _xnUSBOpenEndPoint in XnUSBLinux.o
  "_libusb_get_bus_number", referenced from:
      _xnUSBEnumerateDevices in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_get_device", referenced from:
      _xnUSBOpenEndPoint in XnUSBLinux.o
  "_libusb_get_device_address", referenced from:
      _xnUSBEnumerateDevices in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_get_device_descriptor", referenced from:
      FindDevice(unsigned short, unsigned short, void_, libusb_device**) in XnUSBLinux.o
      _xnUSBEnumerateDevices in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_get_device_list", referenced from:
      FindDevice(unsigned short, unsigned short, void_, libusb_device__) in XnUSBLinux.o
      _xnUSBEnumerateDevices in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_handle_events_timeout", referenced from:
      xnUSBHandleEventsThread(void_) in XnUSBLinux.o
  "_libusb_init", referenced from:
      xnUSBPlatformSpecificInit() in XnUSBLinux.o
  "_libusb_interrupt_transfer", referenced from:
      _xnUSBWriteEndPoint in XnUSBLinux.o
      _xnUSBReadEndPoint in XnUSBLinux.o
  "_libusb_open", referenced from:
      _xnUSBOpenDeviceImpl in XnUSBLinux.o
  "_libusb_ref_device", referenced from:
      FindDevice(unsigned short, unsigned short, void_, libusb_device__) in XnUSBLinux.o
      _xnUSBOpenDeviceByPath in XnUSBLinux.o
  "_libusb_release_interface", referenced from:
      _xnUSBCloseDevice in XnUSBLinux.o
  "_libusb_set_interface_alt_setting", referenced from:
      _xnUSBSetInterface in XnUSBLinux.o
  "_libusb_submit_transfer", referenced from:
      xnUSBReadThreadMain(void_) in XnUSBLinux.o
  "_libusb_unref_device", referenced from:
      _xnUSBIsDevicePresent in XnUSBLinux.o
      _xnUSBOpenDeviceImpl in XnUSBLinux.o
  ld: symbol(s) not found for architecture i386
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[1]: **\* [../../Bin/x64-Release/libOpenNI.dylib] Error 1
  make: **\* [OpenNI] Error 2
  failed to execute: make  -j4 -C /Users/ratulaggarwal/Kinect/OpenNI/Platform/Linux/CreateRedist/../Build > /Users/ratulaggarwal/Kinect/OpenNI/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!

I've been trying to run RedistMaker for about one week now. I'm using Mac OSX Yosemite and I've downloaded OpenNI unstable from Github.

Please help me out with this..
