### ISSUE TITLE
Crash in XnVFeatures64_1_4_2.dll

### ISSUE THREAD

**Issue by zmme** [OpenNI/OpenNI#43]
Hello,

there seems to be an issue within the XnVFeatures64_1_4_2.dll which leads to an application crash at runtime.
Unfortunately I cannot reproduce the behaviour. However, the error seems to appear when there's "a lot to do" for the Kinect e.g. there have been two or more users tracked and some others come into camera scope.

I know this is not that much info, but ...

The context is as follows:
- (Fresh install of) Windows7 64-Bit
- openni-win64-1.3.3.6-dev
- nite-win64-1.4.2.4-dev
- SensorKinect-Win-OpenSource64-5.0.3.4

The system log entry is as follows:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2011-10-13T08:49:11.000000000Z" /> 
  <EventRecordID>1100</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>kinect-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: ETC.Kinect.UI.WPF.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException Stack: at OpenNI.SafeNativeMethods.xnWaitOneUpdateAll(IntPtr, IntPtr) at OpenNI.Context.WaitOneUpdateAll(OpenNI.Generator) at ETC.Kinect.KinectAccess.ReaderThread() at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
  </EventData>
  </Event>
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2011-10-13T08:49:12.000000000Z" /> 
  <EventRecordID>1101</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>kinect-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>ETC.Kinect.UI.WPF.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>4e959d06</Data> 
  <Data>XnVFeatures64_1_4_2.dll</Data> 
  <Data>1.4.2.4</Data> 
  <Data>4e933c62</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000097687</Data> 
  <Data>60c</Data> 
  <Data>01cc88e8ff7fcf0a</Data> 
  <Data>C:\Users\kinect\Desktop\ProjectNoteViewer\ETC.Kinect.UI.WPF.exe</Data> 
  <Data>C:\Program Files\PrimeSense\NITE\Features_1_4_2\Bin64\XnVFeatures64_1_4_2.dll</Data> 
  <Data>38c20e38-f578-11e0-874c-80ee731fe2b5</Data> 
  </EventData>
  </Event>
  Name der fehlerhaften Anwendung: ETC.Kinect.UI.WPF.exe, Version: 1.0.0.0, Zeitstempel: 0x4e959d06
  Name des fehlerhaften Moduls: XnVFeatures64_1_4_2.dll, Version: 1.4.2.4, Zeitstempel: 0x4e933c62
  Ausnahmecode: 0xc0000005
  Fehleroffset: 0x0000000000097687
  ID des fehlerhaften Prozesses: 0x60c
  Startzeit der fehlerhaften Anwendung: 0x01cc88e8ff7fcf0a
  Pfad der fehlerhaften Anwendung: C:\Users\kinect\Desktop\ProjectNoteViewer\ETC.Kinect.UI.WPF.exe
  Pfad des fehlerhaften Moduls: C:\Program Files\PrimeSense\NITE\Features_1_4_2\Bin64\XnVFeatures64_1_4_2.dll
  Berichtskennung: 38c20e38-f578-11e0-874c-80ee731fe2b5

**Comment by OpenNI** [comment]
We just fixed a major memory corruption in NITE on 64-bit machines.
Can you please check the latest unstable version (1.4.2.5) and see if it's okay?
Thanks,
Ziv.
