### ISSUE TITLE
Cannot build OpenNI 1.3.3.6 on ubuntu 10.10 32-bit

### ISSUE THREAD

**Issue by hben8814** [OpenNI/OpenNI#45]
Hi there, I have been trying to install OpenNI 1.3.3.6, but when executing "RedistMaker" or "make" in Build directory, always shows me:

---
-   PrimeSense OpenNI Redist    *
-     2011-10-15 10:58:25       *
  *********************************
- Taking version...
  version is 1.3.3.6
- Building OpenNI...
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:5: fatal error: xnLog.h: File not exists
  compilation terminated.
  make[1]: **\* [Release/XnDumpFileWriter.o] Error 1
  make: **\* [OpenNI] Error 2
  failed to execute: make PLATFORM=x86 -C ../Build > /home/herman/Tesis/Development/Kinect/OpenNI/Platform/Linux-x86/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!

I checked Source/OpenNI/XnDumpFileWriter.cpp file, and in line 5:
# include &lt;xnLog.h&gt;

So in Include directory only exists "XnLog.h" with "X", no "x", so ichanged it, and I got more erros:

---
-   PrimeSense OpenNI Redist    *
-     2011-10-15 11:08:09       *
  *********************************
- Taking version...
  version is 1.3.3.6
- Building OpenNI...
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual XnDumpWriterFileHandle XnDumpFileWriter::OpenFile(const XnChar_, XnBool, const XnChar_)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:25: error: invalid conversion from ‘XN_FILE_HANDLE’ to ‘void_’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::Write(XnDumpWriterFileHandle, const XnUInt8_, XnUInt32)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:33: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp: In member function ‘virtual void XnDumpFileWriter::CloseFile(XnDumpWriterFileHandle)’:
  ../../../../Source/OpenNI/XnDumpFileWriter.cpp:39: error: invalid conversion from ‘void_’ to ‘XN_FILE_HANDLE’
  make[1]: **\* [Release/XnDumpFileWriter.o] Error 1
  make: **\* [OpenNI] Error 2
  failed to execute: make PLATFORM=x86 -C ../Build > /home/herman/Tesis/Development/Kinect/OpenNI/Platform/Linux-x86/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!

And I don't know what to do.

Please I need help because I have been cleaning and formating my computer many times, and the previous version of OpenNI 1.3.2.1 worked fine, I don't know how to fix the error.

Thank you

**Comment by OpenNI** [comment]
Fixed... sorry about that :-)
Please get the new sources.
Ziv.
