### ISSUE TITLE
Playing from a recorded .oni file does't work after updating to 1.3.4.3 in unstable

### ISSUE THREAD

**Issue by ushadow** [OpenNI/OpenNI#46]
After updating to version 1.3.4.3 in the unstable branch, I got the following error when running NiViewer with a specified .oni file in the <Recording> tag.

Open failed: failed to open the file!

It works fine when I switch to the latest version in the master branch with the memmove patch.

OS: Ubuntu 11.10
Kinect driver: SensorKinect latest unstable branch

**Comment by OpenNI** [comment]
You are right, it was a bug and it's now fixed in the latest unstable 1.3.4.6 version.

P.S.
Going to look at the memmove patch soon and integrate it as well.

**Comment by ushadow** [comment]
Thanks!

**Comment by Shubhampatni86** [comment]
can any one suggest how to use *.oni files?..is it related with autocalibration?
