### ISSUE TITLE
xn::IRMetaData miss operator() and operator[]

### ISSUE THREAD

**Issue by KHeresy** [OpenNI/OpenNI#49]
Both xn::DepthMetaData and xn::SceneMetaData have operator() and operator[] for access data.
But xn::IRMetaData don't have these two operators.

Recommand:
Add operator() and operator[] in xn::IRMetaData for the interface consistent.

**Comment by OpenNI** [comment]
You are right, we have fixed it.
It will be out in the next version.
Thanks!
Ziv.
