### ISSUE TITLE
Problems on MacOS

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [OpenNI/OpenNI#7]
Hello, i´m trying to compile under XOS and I´m getting this error:

---
-   PrimeSense OpenNI Redist    *
-     2011-01-05 17:11:35       *
  *********************************
- Taking version...
  version is 1.0.0.25
- Building OpenNI...
  make[1]: Nothing to be done for `all'.
- Creating Doxygen...
  /Users/Patricio/Downloads/OpenNI-OpenNI-1fc853c/Include/XnPrdNode.h:1175: warning: The following parameters of xnEnumerateAllGestures(XnNodeHandle hInstance, XnChar *_pstrGestures, XnUInt32 nNameLength, XnUInt16 *nGestures) are not documented:
  parameter 'nNameLength'
  /Users/Patricio/Downloads/OpenNI-OpenNI-1fc853c/Include/XnPrdNode.h:1159: warning: The following parameters of xnGetAllActiveGestures(XnNodeHandle hInstance, XnChar *_pstrGestures, XnUInt32 nNameLength, XnUInt16 _nGestures) are not documented:
  parameter 'nNameLength'
  /Users/Patricio/Downloads/OpenNI-OpenNI-1fc853c/Include/XnPrdNode.h:1618: warning: The following parameters of xnGetAllAvailablePoses(XnNodeHandle hInstance, XnChar *_pstrPoses, XnUInt32 nNameLength, XnUInt32 *pnPoses) are not documented:
  parameter 'nNameLength'
  sh: C:\Program Files\HTML Help Workshop\hhc.exe: command not found
  error: failed to run html help compiler on index.hhp
- Creating Redist Dir...
- Copying files to redist dir...
  Samples: ['.DS_Store', 'NiAudioSample', 'NiBackRecorder', 'NiConvertXToONI', 'NiCRead', 'NiRecordSynthetic', 'NiSampleModule', 'NiSimpleCreate', 'NiSimpleRead', 'NiSimpleViewer', 'NiUserTracker', 'NiViewer']
  Traceback (most recent call last):
  File "Redist_OpenNi.py", line 270, in <module>
    shutil.copytree("../../Samples/" + sample, "Redist/Samples/" + sample)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/shutil.py", line 140, in copytree
    names = os.listdir(src)
  OSError: [Errno 20] Not a directory: '../../Samples/.DS_Store'

Any idea what´s it means?

Update:
Removing ../../Samples/.DS_Store fix this issue.
Now I´m stock getting how to make the examples to work

**Comment by pattec22** [comment]
I'm having this same issue and it hasn't been resolved.  I'm having a hard time removing .DS_Store

**Comment by patriciogonzalezvivo** [comment]
Have you try using terminal comand "rm .DS_Store"

Finaly I get to work every thing thanks to: https://github.com/avin2/SensorKinect
that compiles the specific driver for Kinect

**Comment by pattec22** [comment]
wow...thought i had but apparently not.  that fixed everything.  and i'm also using avin's driver, it's working great.  so far all the samples i've tested are running fine

**Comment by plural** [comment]
The proper link for avin2's SensorKinect repo is https://github.com/avin2/SensorKinect
