### ISSUE TITLE
Samples: More efficient OpenGL texture update

### ISSUE THREAD

**Issue by HorstBaerbel** [OpenNI/OpenNI#72]
I noticed the "NiHandTracker" sample was quite slow (Ubuntu 12.04, Intel Core i3 with HD2000 IGP). While diggin into the source code I noticed the texture is updated inefficiently. I'd suggest doing it like this:

In "NiSimpleViewer.cpp::InitOpenGL()" create the texture with GL_LINEAR filtering only and do not enable automatic mipmap creation:

``` C++
//glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP_SGIS, GL_TRUE);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR); // not GL_LINEAR_MIPMAP_LINEAR
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
glTexImage2D(GL_TEXTURE_2D, 0, 3, m_nTexMapX, m_nTexMapY, 0, GL_RGB, GL_UNSIGNED_BYTE, m_pTexMap);
```

then when updating the texture in "NiSimpleViewer.cpp::Display()" just update the level 0 using glTextSubImage2D:

``` C++
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, m_nTexMapX, m_nTexMapY, GL_RGB, GL_UNSIGNED_BYTE, m_pTexMap);
```

Best Regards,

Kim

**Comment by xhava** [comment]
hi u know how can i run the sampler to be sure if openni works on my computer thanks
