### ISSUE TITLE
error compiling on ARM

### ISSUE THREAD

**Issue by anupkini** [OpenNI/OpenNI#81]
Hi,

I am trying to build OpenNI drivers fro Kinect and facing he following errors.
Let me know if any one has faced a similar issue and found a solution.

make[1]: Entering directory `/home/linaro/openni_ros/drivers/openni'
git clone https://github.com/OpenNI/OpenNI.git build/openni
Cloning into 'build/openni'...
remote: Counting objects: 4866, done.
remote: Compressing objects: 100% (1890/1890), done.
remote: Total 4866 (delta 2995), reused 4312 (delta 2509)
Receiving objects: 100% (4866/4866), 76.93 MiB | 879 KiB/s, done.
Resolving deltas: 100% (2995/2995), done.
cd build/openni && git checkout 7409554df0761bca0213c900189885ff3c4ac852 
Checking out files: 100% (1143/1143), done.
Note: checking out '7409554df0761bca0213c900189885ff3c4ac852'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 7409554... Fixed missing files from the Linux common directory.
touch rospack_nosubdirs
cd build/openni && git reset --hard
HEAD is now at 7409554 Fixed missing files from the Linux common directory.
patch -d build/openni -p1 < patch.pointclouds.org &&  echo patched
patching file Include/Linux-x86/XnPlatformLinux-x86.h
patching file Include/XnOS.h
patching file Include/XnPlatform.h
patching file Include/XnTypes.h
patching file Platform/Linux/Build/Common/Platform.x86
patching file Platform/Linux/Build/Makefile
patching file Platform/Linux/CreateRedist/Redist_OpenNi.py
patching file Samples/NiAudioSample/NiAudioSample.cpp
patching file Samples/NiCRead/NiCRead.c
patching file Samples/NiHandTracker/main.cpp
patching file Samples/NiRecordRaw/NiRecordRaw.cpp
patching file Samples/NiRecordSynthetic/NiRecordSynthetic.cpp
patching file Samples/NiSimpleRead/NiSimpleRead.cpp
patching file Samples/NiSimpleSkeleton/NiSimpleSkeleton.cpp
patching file Samples/NiSimpleViewer/NiSimpleViewer.cpp
patching file Samples/NiUserSelection/UserTracker.cpp
patching file Samples/NiUserTracker/main.cpp
patching file Samples/NiViewer/NiViewer.cpp
patching file Samples/SimpleRead.java/org/OpenNI/Samples/SimpleRead/SimpleRead.java
patching file Samples/SimpleViewer.java/org/OpenNI/Samples/SimpleViewer/SimpleViewerApplication.java
patching file Samples/UserTracker.java/org/OpenNI/Samples/UserTracker/UserTracker.java
patching file Samples/UserTracker.java/org/OpenNI/Samples/UserTracker/UserTrackerApplication.java
patching file Source/OpenNI/XnOpenNI.cpp
patching file Wrappers/OpenNI.java/src/org/OpenNI/NodeInfoList.java
patching file Wrappers/OpenNI.java/src/org/OpenNI/Observable.java
patched
touch rospack_nosubdirs
touch patched
cd build/openni/Platform/Linux/CreateRedist && bash RedistMaker && cd -

---
-   PrimeSense OpenNI Redist    *
-     2013-01-16 11:44:05       *
  *********************************

Target: Linux-Arm
Version: 1.5.4.0
Num of compile jobs: 4
- Building OpenNI...
  In file included from /usr/include/unistd.h:26:0,
               from ../../../../Include/Linux-Arm/../Linux-x86/XnPlatformLinux-x86.h:32,
               from ../../../../Include/Linux-Arm/XnPlatformLinux-Arm.h:26,
               from ../../../../Include/XnPlatform.h:68,
               from ../../../../Include/XnDump.h:28,
               from ../../../../Include/XnDumpWriters.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.h:7,
               from ../../../../Source/OpenNI/XnDumpFileWriter.cpp:4:
  /usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
  In file included from /usr/include/unistd.h:26:0,
               from ../../../../Include/Linux-Arm/../Linux-x86/XnPlatformLinux-x86.h:32,
               from ../../../../Include/Linux-Arm/XnPlatformLinux-Arm.h:26,
               from ../../../../Include/XnPlatform.h:68,
               from ../../../../Include/XnStatus.h:25,
               from ../../../../Include/XnTypes.h:28,
               from ../../../../Include/XnEnumerationErrors.h:28,
               from ../../../../Source/OpenNI/XnEnumerationErrors.cpp:25:

/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.

In file included from /usr/include/unistd.h:26:0,
                 from ../../../../Include/Linux-Arm/../Linux-x86/XnPlatformLinux-x86.h:32,
                 from ../../../../Include/Linux-Arm/XnPlatformLinux-Arm.h:26,
                 from ../../../../Include/XnPlatform.h:68,
                 from ../../../../Include/XnOS.h:28,
                 from ../../../../Include/XnDataTypes.h:28,
                 from ../../../../Include/XnBaseNode.h:27,
                 from ../../../../Source/OpenNI/XnBaseNode.cpp:22:

/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.

In file included from /usr/include/unistd.h:26:0,
                 from ../../../../Include/Linux-Arm/../Linux-x86/XnPlatformLinux-x86.h:32,
                 from ../../../../Include/Linux-Arm/XnPlatformLinux-Arm.h:26,
                 from ../../../../Include/XnPlatform.h:68,
                 from ../../../../Include/XnDump.h:28,
                 from ../../../../Source/OpenNI/XnDump.cpp:25:

/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory

compilation terminated.
compilation terminated.

make[3]: **\* [Arm-Release/XnBaseNode.o] Error 1

make[3]: **\* Waiting for unfinished jobs....

make[3]: **\* [Arm-Release/XnEnumerationErrors.o] Error 1

make[3]: **\* [Arm-Release/XnDumpFileWriter.o] Error 1

make[3]: **\* [Arm-Release/XnDump.o] Error 1

make[2]: **\* [OpenNI] Error 2

failed to execute: make  -j4 -C /home/linaro/openni_ros/drivers/openni/build/openni/Platform/Linux/CreateRedist/../Build > /home/linaro/openni_ros/drivers/openni/build/openni/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt

Building Failed!
make[1]: **\* [installed] Error 1
make[1]: Leaving directory `/home/linaro/openni_ros/drivers/openni'
make: **\* [openni_lib] Error 2
linaro@linaro-ubuntu-desktop:~/openni_ros/drivers$

**Comment by eddiecohen** [comment]
Here's the error message you got:

/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.

In file included from /usr/include/unistd.h:26:0,

Seems to me that your /usr/include/unistd.h has a "include <bits/predefs.h>" line at line 26, and for some reason, you don't have this file (bits/predefs.h). This has nothing to do with OpenNI itself.

**Comment by anupkini** [comment]
Thanks fo pointing out to the missing files, they were present but were not linked fro som reason.
I solved the error by installin libc6-dev-armhf related libs.

Now further along the process, there are some linking issues.
/usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register arguments, ./Arm-Release/XnBaseNode.o does not
/usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnBaseNode.o
/usr/bin/ld: error: ../../Bin/Arm-Release/libOpenNI.so uses VFP register arguments, ./Arm-Release/XnDump.o does not
/usr/bin/ld: failed to merge target specific data of file ./Arm-Release/XnDump.o

and many more of such linker issues...

Is this a known issue or am i missing something here.

**Comment by eddiecohen** [comment]
You're probably compiling on a linaro version newer than 12.x. Linaro had switched to hard-floats. Try removing the "-mfloat-abi=softfp" flag from Platform/Linux/Build/Common/Platform.ARM file.

**Comment by anupkini** [comment]
Hi Eddie Cohen,

Thanks for the support.
I have now compiled and installed OpenNI successfully.

Now, heading towards installing and compiling ps_engine and Nite.

On 16 January 2013 16:32, eddiecohen notifications@github.com wrote:

> You're probably compiling on a linaro version newer than 12.x. Linaro had
> switched to hard-floats. Try removing the "-mfloat-abi=softfp" flag from
> Platform/Linux/Build/Common/Platform.ARM file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OpenNI/OpenNI/issues/81#issuecomment-12323497.

## 

_Anup Kini
*Systems Engineer_***

## *

*

_Synapticon_\* \* |  Cyber-Physical System Solutions ****

Direct:****

+49 7335 / 186 999 17****

Fax:****
+49 7335 / 186 999 1

---

---

synapticon.com http://www.synapticon.com/  |
@synapticon_cohttps://twitter.com/#!/synapticon_co

---

Synapticon GmbH  |  Hohlbachweg 2  |  73344 Gruibingen, DE
Secretary +49 7335 / 186 999 0  |  General Manager: Nikolai Ensslen
Registry Court Ulm HRB 725114  |  USt-ID DE271647127****

This message and any files transmitted with it are confidential and
intended
solely for the use of the individual or entity to whom they are addressed.
Please notify the sender immediately if you have received this e-mail by
mistake and delete it from your system.
