### ISSUE TITLE
Poor accuracy of tracking certain joints

### ISSUE THREAD

**Issue by chriskilding** [OpenNI/OpenNI#83]
We are doing an interdisciplinary project using OpenNI to develop a movement analysis tool, but are struggling with the way certain joints are tracked in the skeleton. Specifically it is good at tracking extremities, but we are finding it is not registering isolated movement of the shoulders, hips, or spine very well.

Based on my (tenuous) understanding of the Kinect / OpenNI stack I would guess this is a problem in NITE, but I could be wrong.

Basically, is there a way to fix this to get more accurate tracking of the joints mentioned above, or failing that - if the problem happens to lie in an open source part of the stack - anything we can do to improve the tracking of these joints in the source code?

(We are using OpenNI 1.5.4 on OS X through the ZigFu plugin, so can't easily change the versions of any components ourselves right now, but if we were to allocate a developer to hack on OpenNI to fix this obviously they could work with all the latest versions.)

**Comment by eddiecohen** [comment]
As you said, this is a problem in NiTE and not in OpenNI. Unfortunately, NiTE is not open source, so you won't be able to fix that yourself.

You can try using NiTE output as a starting point, and use the user pixels map and depth map to try and fix those joints...
