### ISSUE TITLE
CAPI compilation issue in OniCTypes.h 

### ISSUE THREAD

**Issue by msemegen** [OpenNI/OpenNI#89]
Lines 85 - 92 (actual):

```
struct _OniDevice;
typedef _OniDevice* OniDeviceHandle;

struct _OniStream;
typedef _OniStream* OniStreamHandle;

struct _OniRecorder;
typedef _OniRecorder* OniRecorderHandle;
```

Should be:

```
struct _OniDevice;
typedef struct _OniDevice* OniDeviceHandle;

struct _OniStream;
typedef struct _OniStream* OniStreamHandle;

struct _OniRecorder;
typedef struct _OniRecorder* OniRecorderHandle;
```

Actual version does not compile on Microsoft Visual Studio 2012, when pure C compilation is on. Didn't check on others platforms / compilers.

**Comment by eddiecohen** [comment]
You probably meant to open this at https://github.com/OpenNI/OpenNI2.
In any case, it's already fixed there in the 'develop' branch.
