### ISSUE TITLE
Cannot compile on OSX Snow Leopard

### ISSUE THREAD

**Issue by jslauthor** [OpenNI/OpenNI#9]
Hey all,

I can't seem to compile on OSX. When I run the CreateRedist script, I get the following: 

---
-   PrimeSense OpenNI Redist    *
-     2011-01-26 17:00:55       *
  *********************************
- Taking version...
  .23sion is 1
- Building OpenNI...
  ../../../../Source/OpenNI/XnBaseNode.cpp:1: error: -malign-double makes no sense in the 64bit mode
  make[1]: **\* [Release/XnBaseNode.o] Error 1
  make: **\* [OpenNI] Error 2
  g++ -MD -MP -MT "./Release/XnBaseNode.d Release/XnBaseNode.o" -c -malign-double -fPIC -fvisibility=hidden -O2 -DNDEBUG -msse3 -I../../../../Include -I../../../../Source -I../../../../Source/External/TinyXml -DXN_EXPORTS -o Release/XnBaseNode.o ../../../../Source/OpenNI/XnBaseNode.cpp

Building Failed!!

-END-

If I add the cflag -m32, it doesn't give that error anymore, but a load of compile errors, the first being: 

../../../../Include/XnPlatform.h:70:3: error: #error OpenNI Platform Abstraction Layer - Unsupported Platform!

Any ideas? Thanks!

Best,
Leonard

**Comment by johnlinvc** [comment]
Hi

Seems Like you use the wrong branch
You should use unstable branch instead

git checkout unstable

johnlinvc
